name: "Terraform Deploy to Azure"

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./network-foundation
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ado_url=https://dev.azure.com/20200509" -var="key_vault_id=dummy-key-vault-id" -var="onprem_gateway_ip=8.8.8.8"
